### PR TITLE
added loader at signin and signup pages

### PR DESCRIPTION
**Pull request by shootermv**
image

### CODE REVIEW

**Comment by shootermv** [comment]
something wrong with my UX design?

**Comment by spencercarli** [comment]
Whoops! Missed your PR. I'll try and review it soon.

**Comment by spencercarli** [comment]
Merged. Thanks for your patience.

**Comment by spencercarli** [comment]
FYI I made a few small changes https://github.com/ReactNativeSchool/react-native-ecommerce-app/commit/8c19b5d302f65efdbbd44e44a685316079364325

**Pull request merged**
